// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJATwalujDVSwabFinTFyON_B7u-yflGI',
    appId: '1:1006831584516:web:660da5ae4a0df2eabfbc51',
    messagingSenderId: '1006831584516',
    projectId: 'job-finder-adeeb',
    authDomain: 'job-finder-adeeb.firebaseapp.com',
    storageBucket: 'job-finder-adeeb.firebasestorage.app',
    measurementId: 'G-47XG3T37VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ADML9Op75jBuWb_ikV88mtSxIaLhOKo',
    appId: '1:1006831584516:android:9bf505d86913c72fbfbc51',
    messagingSenderId: '1006831584516',
    projectId: 'job-finder-adeeb',
    storageBucket: 'job-finder-adeeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARyRrPDVnkhcw8743QONnqUuDhn_vWEIs',
    appId: '1:1006831584516:ios:0118cc68560f8a0ebfbc51',
    messagingSenderId: '1006831584516',
    projectId: 'job-finder-adeeb',
    storageBucket: 'job-finder-adeeb.firebasestorage.app',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARyRrPDVnkhcw8743QONnqUuDhn_vWEIs',
    appId: '1:1006831584516:ios:0118cc68560f8a0ebfbc51',
    messagingSenderId: '1006831584516',
    projectId: 'job-finder-adeeb',
    storageBucket: 'job-finder-adeeb.firebasestorage.app',
    iosBundleId: 'com.example.jobFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJATwalujDVSwabFinTFyON_B7u-yflGI',
    appId: '1:1006831584516:web:1510a8268fb47ae5bfbc51',
    messagingSenderId: '1006831584516',
    projectId: 'job-finder-adeeb',
    authDomain: 'job-finder-adeeb.firebaseapp.com',
    storageBucket: 'job-finder-adeeb.firebasestorage.app',
    measurementId: 'G-XSKBGZ4EX6',
  );
}
